/**
 * @file src/questionnaire/questions.ts
 * @description Master catalog of questionnaire steps and question definitions.
 * Includes explicit must-set questions (~10) and adaptive questions gated by condition predicates.
 */

import { QuestionDefinition, StepDefinition } from './types';

export const QUESTIONNAIRE_STEPS: StepDefinition[] = [
  {
    id: 'loan_goal',
    number: 1,
    title: 'Loan Goal',
    subtitle: 'Purpose & Target Amount',
    description: 'Tell us why you are borrowing and how much capital you are considering.',
  },
  {
    id: 'borrower_profile',
    number: 2,
    title: 'Borrower Profile',
    subtitle: 'Age & Income Type',
    description: 'We adapt questions specifically for salaried, self-employed, and gig livelihoods.',
  },
  {
    id: 'income_details',
    number: 3,
    title: 'Income & Cash Flow',
    subtitle: 'Net Earnings & Stability',
    description: 'Understand your monthly take-home cash flow and income resilience.',
  },
  {
    id: 'existing_obligations',
    number: 4,
    title: 'Existing Obligations',
    subtitle: 'Current EMIs & Debt Load',
    description: 'Check existing repayment commitments to determine your true remaining capacity.',
  },
  {
    id: 'credit_profile',
    number: 5,
    title: 'Credit Profile',
    subtitle: 'CIBIL / Credit History',
    description: 'Your credit standing helps anchor fair interest rate bands. Unknown is completely okay.',
  },
  {
    id: 'affordability_expenses',
    number: 6,
    title: 'Living Expenses',
    subtitle: 'Household Budget & Buffer',
    description: 'Your living costs define the boundary between safe borrowing and default risk.',
  },
  {
    id: 'loan_specific_collateral',
    number: 7,
    title: 'Collateral & Purpose',
    subtitle: 'Asset Pledging & Return',
    description: 'Explore collateral security to negotiate lower interest rates and verify productivity.',
  },
  {
    id: 'lender_offer',
    number: 8,
    title: 'Lender Offer (Optional)',
    subtitle: 'Existing Bank Quotes',
    description: 'If a bank or NBFC has given you a quotation, compare it against fair market APR.',
  },
  {
    id: 'review',
    number: 9,
    title: 'Review Profile',
    subtitle: 'Final Verification',
    description: 'Review your collected inputs before running the copilot rules assessment.',
  },
];

export const QUESTION_DEFINITIONS: QuestionDefinition[] = [
  // =========================================================================
  // STEP 1: LOAN GOAL
  // =========================================================================
  {
    id: 'purpose',
    stepId: 'loan_goal',
    stepTitle: 'Loan Goal',
    text: 'What do you need the loan for?',
    description: 'Different loan purposes carry different financial risks and return characteristics.',
    helpText: 'Helps us distinguish discretionary spending from productive investments.',
    type: 'single_choice',
    required: true,
    isMust: true,
    options: [
      { value: 'wedding_or_family_event', label: 'Wedding or Family Event', sublabel: 'Discretionary, one-time social expenditure' },
      { value: 'business_expansion', label: 'Business / Productive Use', sublabel: 'Inventory, equipment, or enterprise growth' },
      { value: 'asset_purchase', label: 'Asset Purchase', sublabel: 'Vehicle, tools, machinery, or long-term asset' },
      { value: 'debt_consolidation', label: 'Debt Consolidation', sublabel: 'Paying off high-cost or predatory loans' },
      { value: 'emergency_or_medical', label: 'Medical or Emergency', sublabel: 'Urgent family healthcare or contingency' },
      { value: 'other', label: 'Personal Consumption / Other', sublabel: 'Travel, home renovation, or general use' },
    ],
    affects: ['verdict', 'borrowerSafeAmount'],
    confidenceImpact: 'high',
  },
  {
    id: 'loanType',
    stepId: 'loan_goal',
    stepTitle: 'Loan Goal',
    text: 'What type of loan are you considering?',
    description: 'Product structure dictates whether collateral can reduce your borrowing interest rate.',
    helpText: 'Secured products typically command 2%–4% lower interest rates than unsecured personal loans.',
    type: 'single_choice',
    required: true,
    isMust: true,
    options: [
      { value: 'personal_loan', label: 'Unsecured Personal Loan', sublabel: 'No collateral required; based purely on income & CIBIL' },
      { value: 'business_loan', label: 'Business Term Loan / MSME', sublabel: 'Working capital or term debt for enterprise' },
      { value: 'home_or_lap', label: 'Loan Against Property (LAP) / Home Loan', sublabel: 'Secured against residential or commercial real estate' },
      { value: 'vehicle_loan', label: 'Two-Wheeler / Car / Commercial Vehicle', sublabel: 'Hypothecated vehicle financing' },
      { value: 'gold_loan', label: 'Gold Loan', sublabel: 'Instant secured loan against physical gold jewellery' },
      { value: 'digital_micro_loan', label: 'Digital App / Instant Micro Loan', sublabel: 'Quick disbursement via smartphone app' },
    ],
    affects: ['fairRateBand', 'allInAPR', 'borrowerSafeAmount'],
    confidenceImpact: 'high',
  },
  {
    id: 'amountRequested',
    stepId: 'loan_goal',
    stepTitle: 'Loan Goal',
    text: 'How much do you want to borrow?',
    description: 'Enter the exact principal amount you are planning to request from lenders.',
    helpText: 'We will compare this target against your lender sanction limit and borrower-safe limit.',
    type: 'currency',
    required: true,
    isMust: true,
    min: 10000,
    max: 50000000,
    placeholder: 'e.g. 5,00,000',
    affects: ['verdict', 'borrowerSafeAmount', 'stressCase'],
    confidenceImpact: 'high',
    validation: (val) => {
      if (!val || val <= 0) return 'Loan amount must be greater than zero.';
      if (val < 10000) return 'Minimum evaluation loan amount is ₹10,000.';
      return null;
    },
  },
  {
    id: 'tenureWantedMonths',
    stepId: 'loan_goal',
    stepTitle: 'Loan Goal',
    text: 'Preferred repayment tenure',
    description: 'Longer tenures reduce monthly EMI but drastically inflate total interest paid.',
    helpText: 'Select your preferred duration. We will also benchmark alternatives.',
    type: 'single_choice',
    required: false,
    isMust: false,
    options: [
      { value: 12, label: '12 Months (1 Year)', sublabel: 'Fastest payoff, lowest total interest' },
      { value: 24, label: '24 Months (2 Years)', sublabel: 'Balanced tenure for smaller loans' },
      { value: 36, label: '36 Months (3 Years)', sublabel: 'Standard retail personal loan benchmark' },
      { value: 48, label: '48 Months (4 Years)', sublabel: 'Lower monthly EMI, higher interest' },
      { value: 60, label: '60 Months (5 Years)', sublabel: 'Maximum personal loan term' },
      { value: 84, label: '84 Months (7 Years)', sublabel: 'Common for secured business / property debt' },
    ],
    affects: ['emiCeiling', 'stressCase'],
    confidenceImpact: 'low',
  },

  // =========================================================================
  // STEP 2: BORROWER PROFILE
  // =========================================================================
  {
    id: 'age',
    stepId: 'borrower_profile',
    stepTitle: 'Borrower Profile',
    text: 'What is your age?',
    description: 'Lenders evaluate earning runway and retirement horizons when setting maximum tenures.',
    helpText: 'Valid working age in India is typically 18 to 70 years.',
    type: 'number',
    required: true,
    isMust: true,
    min: 18,
    max: 75,
    placeholder: 'e.g. 29',
    affects: ['lenderLikelySanction', 'confidence'],
    confidenceImpact: 'low',
    validation: (val) => {
      if (!val) return 'Age is required.';
      if (val < 18) return 'Borrower must be at least 18 years old.';
      if (val > 80) return 'Age must be 80 or below for retail credit assessment.';
      return null;
    },
  },
  {
    id: 'employmentType',
    stepId: 'borrower_profile',
    stepTitle: 'Borrower Profile',
    text: 'What is your employment or income type?',
    description: 'Lending underwriting differs fundamentally between salaried paychecks and enterprise revenues.',
    helpText: 'Select the primary source of your personal cash flow.',
    type: 'single_choice',
    required: true,
    isMust: true,
    options: [
      { value: 'salaried_corporate', label: 'Salaried (Corporate / Tier-1 MNC / Listed / Govt)', sublabel: 'Fixed monthly direct deposit salary slip & Form 16' },
      { value: 'salaried_regular', label: 'Salaried (SME / Private Firm / Startup)', sublabel: 'Regular monthly salary credited to bank account' },
      { value: 'self_employed_business', label: 'Self-Employed Business Owner / Merchant', sublabel: 'Proprietorship, retail shop, trading, or manufacturing' },
      { value: 'self_employed_professional', label: 'Self-Employed Professional', sublabel: 'Doctor, CA, Architect, Lawyer, or Consultant' },
      { value: 'informal_or_gig', label: 'Informal / Freelance / Gig Worker', sublabel: 'Delivery rider, driver, artisan, freelancer, cash income' },
    ],
    affects: ['fairRateBand', 'allInAPR', 'lenderLikelySanction'],
    confidenceImpact: 'high',
  },
  {
    id: 'hasCoapplicant',
    stepId: 'borrower_profile',
    stepTitle: 'Borrower Profile',
    text: 'Will someone apply with you as a co-applicant?',
    description: 'Adding an earning spouse or family member can augment eligible household borrowing capacity.',
    helpText: 'A co-applicant pools their documented income into the institutional debt assessment.',
    type: 'yes_no',
    required: false,
    isMust: false,
    affects: ['borrowerSafeAmount', 'lenderLikelySanction', 'emiCeiling'],
    confidenceImpact: 'moderate',
  },
  {
    id: 'spouseIncome',
    stepId: 'borrower_profile',
    stepTitle: 'Borrower Profile',
    text: 'Co-applicant monthly net income',
    description: 'Enter the co-applicant’s take-home monthly salary or verifiable business earnings.',
    helpText: 'Directly added to total household surplus in the affordability calculation.',
    type: 'currency',
    required: false,
    isMust: false,
    condition: (answers) => answers.hasCoapplicant === true,
    min: 0,
    placeholder: 'e.g. 18,000',
    affects: ['borrowerSafeAmount', 'lenderLikelySanction', 'emiCeiling'],
    confidenceImpact: 'moderate',
  },

  // =========================================================================
  // STEP 3: INCOME & CASH FLOW
  // =========================================================================
  {
    id: 'monthlyNetIncome',
    stepId: 'income_details',
    stepTitle: 'Income & Cash Flow',
    text: 'What is your typical monthly net income?',
    description: 'The take-home amount hitting your bank account or cash drawer after taxes and business costs.',
    helpText: 'The core metric for debt servicing capability.',
    type: 'currency',
    required: true,
    isMust: true,
    min: 1000,
    placeholder: 'e.g. 1,10,000',
    affects: ['borrowerSafeAmount', 'lenderLikelySanction', 'emiCeiling', 'stressCase', 'verdict', 'confidence'],
    confidenceImpact: 'high',
    validation: (val) => {
      if (!val || val <= 0) return 'Net monthly income must be greater than zero.';
      return null;
    },
  },
  {
    id: 'incomeStability',
    stepId: 'income_details',
    stepTitle: 'Income & Cash Flow',
    text: 'How stable is your income month-to-month?',
    description: 'Predictability determines whether fixed monthly debt obligations pose cash-flow volatility risk.',
    helpText: 'This helps us calibrate how much monthly repayment you can safely carry.',
    type: 'single_choice',
    required: true,
    isMust: true,
    options: [
      { value: 'very_stable', label: 'Very Stable', sublabel: 'Fixed salary or established consistent revenue month after month' },
      { value: 'moderately_stable', label: 'Moderately Stable', sublabel: 'Slight seasonal swings (10%–20% variation)' },
      { value: 'variable', label: 'Highly Variable / Seasonal', sublabel: 'Significant monthly swings depending on contracts, footfalls, or gigs' },
    ],
    affects: ['borrowerSafeAmount', 'emiCeiling', 'confidence'],
    confidenceImpact: 'high',
  },

  // 3A: ADAPTIVE SALARIED PATH
  {
    id: 'yearsAtEmployer',
    stepId: 'income_details',
    stepTitle: 'Income & Cash Flow',
    text: 'How long have you been with your current employer?',
    description: 'Lenders consider tenure over 2–3 years as a prime signal of employment continuity.',
    helpText: 'Longer job stability unlocks prime interest rates (10.5%–11.5%).',
    type: 'single_choice',
    required: false,
    isMust: false,
    condition: (answers) =>
      answers.employmentType === 'salaried_corporate' || answers.employmentType === 'salaried_regular',
    options: [
      { value: 'less_than_1_yr', label: 'Less than 1 year', sublabel: 'Still in probation or recently transitioned' },
      { value: '1_to_3_yrs', label: '1 to 3 years', sublabel: 'Established employment track record' },
      { value: 'more_than_3_yrs', label: 'More than 3 years', sublabel: 'High institutional stability score' },
    ],
    affects: ['fairRateBand', 'confidence'],
    confidenceImpact: 'moderate',
  },
  {
    id: 'hasVariableIncome',
    stepId: 'income_details',
    stepTitle: 'Income & Cash Flow',
    text: 'Is any part of your income variable (bonuses, incentives, stock)?',
    description: 'Lenders discount non-guaranteed bonuses when assessing fixed monthly debt service.',
    helpText: 'Ensures we base safe EMIs on guaranteed base pay.',
    type: 'yes_no',
    required: false,
    isMust: false,
    condition: (answers) =>
      answers.employmentType === 'salaried_corporate' || answers.employmentType === 'salaried_regular',
    affects: ['stressCase', 'confidence'],
    confidenceImpact: 'low',
  },
  {
    id: 'hasUpcomingExpenseRisk',
    stepId: 'income_details',
    stepTitle: 'Income & Cash Flow',
    text: 'Do you anticipate major income drops or large unplanned expenses in the next 12 months?',
    description: 'Such as career breaks, childbirth, higher education, or relocating.',
    helpText: 'Highlights sensitivity in our adverse scenario stress-testing.',
    type: 'yes_no',
    required: false,
    isMust: false,
    condition: (answers) =>
      answers.employmentType === 'salaried_corporate' || answers.employmentType === 'salaried_regular',
    affects: ['stressCase', 'confidence'],
    confidenceImpact: 'moderate',
  },

  // 3B: ADAPTIVE SELF-EMPLOYED PATH
  {
    id: 'businessVintageYears',
    stepId: 'income_details',
    stepTitle: 'Income & Cash Flow',
    text: 'How long has the business been operating?',
    description: 'Institutional banks require a minimum 3-year operating vintage to qualify for prime MSME rates.',
    helpText: 'Businesses operating over 5 years enjoy significantly higher lender confidence.',
    type: 'single_choice',
    required: false,
    isMust: false,
    condition: (answers) =>
      answers.employmentType === 'self_employed_business' ||
      answers.employmentType === 'self_employed_professional',
    options: [
      { value: 'less_than_2_yrs', label: 'Less than 2 years', sublabel: 'Early-stage enterprise / startup' },
      { value: '2_to_5_yrs', label: '2 to 5 years', sublabel: 'Proven operating history' },
      { value: 'more_than_5_yrs', label: 'More than 5 years', sublabel: 'Established local commercial presence' },
    ],
    affects: ['lenderLikelySanction', 'confidence'],
    confidenceImpact: 'high',
  },
  {
    id: 'documentedAnnualIncome',
    stepId: 'income_details',
    stepTitle: 'Income & Cash Flow',
    text: 'What is your documented annual ITR / tax return net profit?',
    description: 'Banks calculate credit sanctions strictly from Income Tax Returns (ITR), not self-reported cash.',
    helpText: 'Leave empty or enter 0 if you do not file ITR or deal predominantly in cash.',
    type: 'currency',
    required: false,
    isMust: false,
    allowUnknown: true,
    unknownLabel: 'Do not file ITR / Cash only',
    condition: (answers) =>
      answers.employmentType === 'self_employed_business' ||
      answers.employmentType === 'self_employed_professional',
    min: 0,
    placeholder: 'e.g. 4,20,000',
    affects: ['lenderLikelySanction', 'confidence'],
    confidenceImpact: 'high',
  },
  {
    id: 'businessVariablePercent',
    stepId: 'income_details',
    stepTitle: 'Income & Cash Flow',
    text: 'What percentage of your business revenue is seasonal or variable?',
    description: 'High cash flow volatility requires a wider liquidity cushion to prevent loan defaults.',
    helpText: 'Used to calibrate the cash flow buffer in your safe borrowing recommendation.',
    type: 'single_choice',
    required: false,
    isMust: false,
    condition: (answers) =>
      answers.employmentType === 'self_employed_business' ||
      answers.employmentType === 'self_employed_professional',
    options: [
      { value: 'low_under_20', label: 'Low (< 20% variation)', sublabel: 'Predictable recurring turnover year-round' },
      { value: 'moderate_20_50', label: 'Moderate (20%–50% variation)', sublabel: 'Festival peaks or quarterly fluctuations' },
      { value: 'high_over_50', label: 'High (> 50% seasonal swings)', sublabel: 'Heavily dependent on monsoon, harvest, or holidays' },
    ],
    affects: ['stressCase', 'confidence'],
    confidenceImpact: 'moderate',
  },
  {
    id: 'hasBusinessDebt',
    stepId: 'income_details',
    stepTitle: 'Income & Cash Flow',
    text: 'Do you have existing business overdrafts, CC limits, or vendor debt?',
    description: 'Commercial credit lines count toward total enterprise debt service burden.',
    helpText: 'Prevents over-leveraging of shop inventory and assets.',
    type: 'yes_no',
    required: false,
    isMust: false,
    condition: (answers) =>
      answers.employmentType === 'self_employed_business' ||
      answers.employmentType === 'self_employed_professional',
    affects: ['borrowerSafeAmount', 'emiCeiling'],
    confidenceImpact: 'moderate',
  },

  // 3C: ADAPTIVE INFORMAL / GIG PATH
  {
    id: 'lowestMonthlyIncome',
    stepId: 'income_details',
    stepTitle: 'Income & Cash Flow',
    text: 'What is your lowest monthly income in a normal lean month?',
    description: 'In slow months or during illness, fixed loan EMIs must still be paid.',
    helpText: 'Helps ensure you never take on an EMI that exceeds your leanest month’s surplus.',
    type: 'currency',
    required: false,
    isMust: false,
    condition: (answers) => answers.employmentType === 'informal_or_gig',
    min: 0,
    placeholder: 'e.g. 22,000',
    affects: ['stressCase', 'emiCeiling', 'borrowerSafeAmount'],
    confidenceImpact: 'high',
  },
  {
    id: 'incomeSourceCount',
    stepId: 'income_details',
    stepTitle: 'Income & Cash Flow',
    text: 'How many active income platforms or work clients do you have?',
    description: 'Multiple independent gigs provide diversification against platform deactivations.',
    helpText: 'Measures income concentration risk.',
    type: 'single_choice',
    required: false,
    isMust: false,
    condition: (answers) => answers.employmentType === 'informal_or_gig',
    options: [
      { value: 'single_source', label: 'Single platform / employer', sublabel: 'High concentration vulnerability' },
      { value: '2_to_3_sources', label: '2 to 3 apps or clients', sublabel: 'Moderate diversification' },
      { value: '4_or_more', label: '4 or more diversified sources', sublabel: 'Resilient multi-stream freelance work' },
    ],
    affects: ['confidence'],
    confidenceImpact: 'low',
  },

  // =========================================================================
  // STEP 4: EXISTING OBLIGATIONS
  // =========================================================================
  {
    id: 'existingMonthlyEMIs',
    stepId: 'existing_obligations',
    stepTitle: 'Existing Obligations',
    text: 'How much do you currently pay toward EMIs each month?',
    description: 'Sum of all active personal loans, car/bike loans, consumer durables, and minimum credit card dues.',
    helpText: 'Enter ₹0 if you currently have no running loans or debts.',
    type: 'currency',
    required: true,
    isMust: true,
    min: 0,
    placeholder: 'e.g. 14,000',
    affects: ['borrowerSafeAmount', 'emiCeiling', 'lenderLikelySanction', 'verdict', 'stressCase'],
    confidenceImpact: 'high',
    validation: (val) => {
      if (val === undefined || val === null || val < 0) return 'Existing EMI cannot be negative.';
      return null;
    },
  },
  {
    id: 'hasExistingLoans',
    stepId: 'existing_obligations',
    stepTitle: 'Existing Obligations',
    text: 'Do you have active loans or credit obligations with formal banks/NBFCs?',
    description: 'Identifies loan portfolio complexity and institutional credit track record.',
    helpText: 'Helps determine whether you are credit-tested.',
    type: 'yes_no',
    required: false,
    isMust: false,
    condition: (answers) => Number(answers.existingMonthlyEMIs || 0) > 0,
    affects: ['confidence'],
    confidenceImpact: 'low',
  },
  {
    id: 'hasBounce',
    stepId: 'existing_obligations',
    stepTitle: 'Existing Obligations',
    text: 'Have you had any cheque or ECS / NACH auto-debit bounces in the past 6 months?',
    description: 'Auto-debit bounces are reported instantly to credit bureaus and severely impair loan approvals.',
    helpText: 'If you had an unintentional bounce due to timing, acknowledging it helps protect you from aggressive fees.',
    type: 'yes_no',
    required: false,
    isMust: false,
    affects: ['verdict', 'fairRateBand', 'confidence'],
    confidenceImpact: 'high',
  },
  {
    id: 'hasAppLoans',
    stepId: 'existing_obligations',
    stepTitle: 'Existing Obligations',
    text: 'Do you currently have active loans from instant mobile lending apps?',
    description: 'Instant micro-apps frequently charge 36%–100%+ APR and utilize aggressive debit cycles.',
    helpText: 'We flag predatory high-cost debt traps and recommend urgent debt consolidation.',
    type: 'yes_no',
    required: false,
    isMust: false,
    condition: (answers) =>
      answers.employmentType === 'informal_or_gig' ||
      answers.loanType === 'digital_micro_loan' ||
      Number(answers.existingMonthlyEMIs || 0) > 0,
    affects: ['verdict', 'fairRateBand', 'confidence'],
    confidenceImpact: 'high',
  },

  // =========================================================================
  // STEP 5: CREDIT PROFILE
  // =========================================================================
  {
    id: 'creditScoreKnown',
    stepId: 'credit_profile',
    stepTitle: 'Credit Profile',
    text: 'Do you know your credit score (CIBIL / Experian)?',
    description: 'Credit scores in India range from 300 to 900. If you do not know it, that is completely fine.',
    helpText: 'We NEVER invent a fake score. Unknown information remains explicitly unverified.',
    type: 'single_choice',
    required: true,
    isMust: true,
    options: [
      { value: true, label: 'Yes, I know my score', sublabel: 'Enter your verified 3-digit bureau score' },
      { value: false, label: 'I do not know it', sublabel: 'We will benchmark using demographic proxies without assuming a score' },
    ],
    affects: ['fairRateBand', 'allInAPR', 'confidence'],
    confidenceImpact: 'high',
  },
  {
    id: 'creditScore',
    stepId: 'credit_profile',
    stepTitle: 'Credit Profile',
    text: 'Enter your 3-digit credit score',
    description: 'Prime retail rates (10.5%–12%) typically require a CIBIL score of 750 or higher.',
    helpText: 'Scores below 650 encounter strict lending terms or elevated interest rates.',
    type: 'number',
    required: false,
    isMust: false,
    min: 300,
    max: 900,
    placeholder: 'e.g. 780',
    condition: (answers) => answers.creditScoreKnown === true,
    affects: ['fairRateBand', 'allInAPR', 'lenderLikelySanction', 'confidence'],
    confidenceImpact: 'high',
    validation: (val, answers) => {
      if (answers.creditScoreKnown && (!val || val < 300 || val > 900)) {
        return 'Please enter a valid credit score between 300 and 900.';
      }
      return null;
    },
  },
  {
    id: 'hasRecentMissedPayments',
    stepId: 'credit_profile',
    stepTitle: 'Credit Profile',
    text: 'Have you missed any credit card bills or loan dues in the past 12 months?',
    description: 'Helps narrow interest rate estimation when your exact score is not on hand.',
    helpText: 'Clean repayment history qualifies you for lower interest rates.',
    type: 'yes_no',
    required: false,
    isMust: false,
    condition: (answers) => answers.creditScoreKnown === false,
    affects: ['fairRateBand', 'confidence'],
    confidenceImpact: 'moderate',
  },
  {
    id: 'recentCreditInquiries',
    stepId: 'credit_profile',
    stepTitle: 'Credit Profile',
    text: 'How many loan or credit card applications have you made in the last 3 months?',
    description: 'Multiple hard inquiries in a short window signal credit hunger to automated banking algorithms.',
    helpText: 'Inquiring at 3+ lenders in parallel can temporarily dampen approval odds.',
    type: 'single_choice',
    required: false,
    isMust: false,
    condition: (answers) => answers.creditScoreKnown === false,
    options: [
      { value: 'none', label: 'None (0)', sublabel: 'No recent bureau inquiries' },
      { value: '1_to_2', label: '1 to 2 applications', sublabel: 'Normal comparison shopping' },
      { value: '3_or_more', label: '3 or more applications', sublabel: 'Frequent credit applications' },
    ],
    affects: ['confidence'],
    confidenceImpact: 'low',
  },

  // =========================================================================
  // STEP 6: AFFORDABILITY & LIVING EXPENSES
  // =========================================================================
  {
    id: 'householdExpenses',
    stepId: 'affordability_expenses',
    stepTitle: 'Living Expenses',
    text: 'What are your typical monthly household expenses?',
    description: 'Rent, groceries, utilities, children education, transport, and insurance.',
    helpText: 'This directly determines how much disposable surplus remains for loan repayments.',
    type: 'currency',
    required: true,
    isMust: true,
    min: 0,
    placeholder: 'e.g. 48,000',
    affects: ['borrowerSafeAmount', 'emiCeiling', 'stressCase', 'confidence'],
    confidenceImpact: 'high',
    validation: (val) => {
      if (val === undefined || val === null || val < 0) return 'Household expenses cannot be negative.';
      return null;
    },
  },
  {
    id: 'emergencySavingsMonths',
    stepId: 'affordability_expenses',
    stepTitle: 'Living Expenses',
    text: 'How many months of essential expenses could your savings cover?',
    description: 'An emergency cushion prevents a temporary disruption from turning into a severe loan default.',
    helpText: 'Having 3+ months of buffer significantly increases your debt safety cushion.',
    type: 'single_choice',
    required: false,
    isMust: false,
    options: [
      { value: 'less_than_1_mo', label: 'Less than 1 month', sublabel: 'High liquidity vulnerability' },
      { value: '1_to_3_mo', label: '1 to 3 months', sublabel: 'Modest emergency safety buffer' },
      { value: '3_to_6_mo', label: '3 to 6 months', sublabel: 'Healthy financial emergency cushion' },
      { value: 'more_than_6_mo', label: 'More than 6 months', sublabel: 'Substantial liquid reserves' },
      { value: 'unknown', label: 'I do not know / Not sure', sublabel: 'Uncertain savings balance' },
    ],
    affects: ['confidence', 'stressCase'],
    confidenceImpact: 'moderate',
  },

  // =========================================================================
  // STEP 7: COLLATERAL & PRODUCTIVITY
  // =========================================================================
  {
    id: 'expectedAdditionalIncome',
    stepId: 'loan_specific_collateral',
    stepTitle: 'Collateral & Purpose',
    text: 'How much additional monthly income do you realistically expect this loan to generate?',
    description: 'Productive loans (commercial stock, vehicles, machinery) can generate positive cash flow.',
    helpText: 'Leave empty or 0 if the loan is for consumption, personal use, or uncertain return.',
    type: 'currency',
    required: false,
    isMust: false,
    allowUnknown: true,
    unknownLabel: 'Unknown / Not sure',
    condition: (answers) =>
      answers.purpose === 'business_expansion' || answers.purpose === 'asset_purchase',
    min: 0,
    placeholder: 'e.g. 15,000',
    affects: ['borrowerSafeAmount', 'confidence'],
    confidenceImpact: 'moderate',
  },
  {
    id: 'hasCollateral',
    stepId: 'loan_specific_collateral',
    stepTitle: 'Collateral & Purpose',
    text: 'Do you have an asset that could potentially be used as collateral?',
    description: 'Commercial shop, residential house/plot, vehicle, or physical gold.',
    helpText: 'Offering collateral can reduce your borrowing interest rate by 2.0%–4.0% p.a.',
    type: 'yes_no',
    required: false,
    isMust: false,
    condition: (answers) =>
      answers.loanType === 'business_loan' ||
      answers.loanType === 'home_or_lap' ||
      answers.loanType === 'vehicle_loan' ||
      answers.employmentType === 'self_employed_business',
    affects: ['fairRateBand', 'allInAPR', 'borrowerSafeAmount', 'lenderLikelySanction'],
    confidenceImpact: 'high',
  },
  {
    id: 'collateralType',
    stepId: 'loan_specific_collateral',
    stepTitle: 'Collateral & Purpose',
    text: 'What type of asset can you pledge?',
    description: 'Different asset classes have different institutional Loan-to-Value (LTV) limits.',
    helpText: 'Properties allow up to 60%–70% LTV; vehicles up to 80%; gold up to 75%.',
    type: 'single_choice',
    required: false,
    isMust: false,
    condition: (answers) => answers.hasCollateral === true,
    options: [
      { value: 'commercial_shop', label: 'Commercial Shop / Office Premises', sublabel: 'Shop, warehouse, or commercial building' },
      { value: 'residential_property', label: 'Residential House / Flat / Plot', sublabel: 'Self-occupied or ancestral real estate' },
      { value: 'vehicle', label: 'Commercial / Personal Vehicle', sublabel: 'Hypothecated car, truck, or auto' },
      { value: 'gold', label: 'Physical Gold Jewellery', sublabel: 'Assayed gold ornaments' },
      { value: 'other', label: 'Other Asset / Fixed Deposit', sublabel: 'FD, NSC, or financial securities' },
    ],
    affects: ['fairRateBand', 'lenderLikelySanction'],
    confidenceImpact: 'moderate',
  },
  {
    id: 'collateralValue',
    stepId: 'loan_specific_collateral',
    stepTitle: 'Collateral & Purpose',
    text: 'Approximate unencumbered market value of the asset',
    description: 'Enter the estimated current resale or guideline value of the asset free of other mortgages.',
    helpText: 'Lenders sanction loans against a percentage (LTV) of this valuation.',
    type: 'currency',
    required: false,
    isMust: false,
    condition: (answers) => answers.hasCollateral === true,
    min: 0,
    placeholder: 'e.g. 45,00,000',
    affects: ['lenderLikelySanction', 'borrowerSafeAmount'],
    confidenceImpact: 'high',
  },

  // =========================================================================
  // STEP 8: LENDER OFFER (OPTIONAL NEGOTIATION CARD FEED)
  // =========================================================================
  {
    id: 'hasLenderOffer',
    stepId: 'lender_offer',
    stepTitle: 'Lender Offer',
    text: 'Have you already received a loan offer from a bank or lender?',
    description: 'If you already have a loan quote, we will evaluate whether the rate and fees are fair.',
    helpText: 'Skip or choose "No" if you are in the planning stage before applying.',
    type: 'single_choice',
    required: false,
    isMust: false,
    options: [
      { value: 'no', label: 'No, I am researching options first', sublabel: 'Get fair benchmarks before approaching lenders' },
      { value: 'yes', label: 'Yes, I have an active quote', sublabel: 'Check if you are being overcharged on interest or fees' },
      { value: 'comparing', label: 'I am currently comparing multiple quotes', sublabel: 'Benchmark competing offers' },
    ],
    affects: ['confidence'],
    confidenceImpact: 'none',
  },
  {
    id: 'quotedAmount',
    stepId: 'lender_offer',
    stepTitle: 'Lender Offer',
    text: 'Quoted loan amount',
    description: 'The principal amount the lender or bank offered or sanctioned.',
    helpText: 'We will compare this against your safe borrowing limit.',
    type: 'currency',
    required: false,
    isMust: false,
    allowUnknown: true,
    unknownLabel: "I don't know",
    placeholder: 'e.g. 5,00,000',
    condition: (answers) => answers.hasLenderOffer === 'yes' || answers.hasLenderOffer === 'comparing',
    affects: ['borrowerSafeAmount'],
    confidenceImpact: 'low',
  },
  {
    id: 'quotedRate',
    stepId: 'lender_offer',
    stepTitle: 'Lender Offer',
    text: 'Interest rate (% per year)',
    description: 'Enter the annual interest rate quoted by the lender’s agent.',
    helpText: 'We will verify whether this is reducing balance or a disguised flat rate.',
    type: 'number',
    required: false,
    isMust: false,
    allowUnknown: true,
    unknownLabel: "I don't know",
    min: 5,
    max: 60,
    step: 0.1,
    placeholder: 'e.g. 13.5',
    condition: (answers) => answers.hasLenderOffer === 'yes' || answers.hasLenderOffer === 'comparing',
    affects: ['fairRateBand', 'allInAPR'],
    confidenceImpact: 'moderate',
  },
  {
    id: 'quotedFee',
    stepId: 'lender_offer',
    stepTitle: 'Lender Offer',
    text: 'Processing fee (% of loan)',
    description: 'Upfront loan origination charge (excluding 18% GST).',
    helpText: 'Fair corporate fees are typically 1.0%–1.5%. Anything above 2.5% is excessive.',
    type: 'number',
    required: false,
    isMust: false,
    allowUnknown: true,
    unknownLabel: "I don't know",
    min: 0,
    max: 10,
    step: 0.1,
    placeholder: 'e.g. 1.5',
    condition: (answers) => answers.hasLenderOffer === 'yes' || answers.hasLenderOffer === 'comparing',
    affects: ['allInAPR'],
    confidenceImpact: 'low',
  },
  {
    id: 'quotedTenure',
    stepId: 'lender_offer',
    stepTitle: 'Lender Offer',
    text: 'Tenure (months)',
    description: 'The loan repayment tenure proposed by the lender in months.',
    helpText: 'E.g., 36 months (3 years), 60 months (5 years).',
    type: 'number',
    required: false,
    isMust: false,
    allowUnknown: true,
    unknownLabel: "I don't know",
    min: 6,
    max: 360,
    step: 6,
    placeholder: 'e.g. 36',
    condition: (answers) => answers.hasLenderOffer === 'yes' || answers.hasLenderOffer === 'comparing',
    affects: ['emiCeiling'],
    confidenceImpact: 'low',
  },
  {
    id: 'quotedEMI',
    stepId: 'lender_offer',
    stepTitle: 'Lender Offer',
    text: 'Quoted monthly EMI',
    description: 'The monthly instalment payment quoted by the lender.',
    helpText: 'We compare this against your safe monthly cash flow surplus.',
    type: 'currency',
    required: false,
    isMust: false,
    allowUnknown: true,
    unknownLabel: "I don't know",
    placeholder: 'e.g. 18,500',
    condition: (answers) => answers.hasLenderOffer === 'yes' || answers.hasLenderOffer === 'comparing',
    affects: ['emiCeiling'],
    confidenceImpact: 'moderate',
  },
  {
    id: 'quotedOtherCharges',
    stepId: 'lender_offer',
    stepTitle: 'Lender Offer',
    text: 'Other mandatory charges',
    description: 'Document charges, stamp duty, or insurance bundled into the quote.',
    helpText: 'Mandatory upfront or capitalized charges increase the true all-in APR.',
    type: 'currency',
    required: false,
    isMust: false,
    allowUnknown: true,
    unknownLabel: "I don't know",
    placeholder: 'e.g. 5,000',
    condition: (answers) => answers.hasLenderOffer === 'yes' || answers.hasLenderOffer === 'comparing',
    affects: ['allInAPR'],
    confidenceImpact: 'low',
  },
];
